### ISSUE TITLE
期望增加试听的功能

### ISSUE THREAD

**Issue by slzhou8** [59799517/simple_sq_musuc_plus#5]
首先感谢大佬的项目，点个小星星支持一下！

期望在搜索歌曲后可以点击试听歌曲，有时候歌曲有多个版本，直接下载可能会下载到不是自己想要的版本

**Comment by 59799517** [comment]
以前是有这个功能的 但是周围同类型项目加上了在线播放后都陆续收到了律师函 这个功能就被我关了

**Comment by slzhou8** [comment]
原来如此 了解
